import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const nunitoSans = Nunito_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClerkProvider
        appearance={{
          layout: {
            socialButtonsVariant: "iconButton",
            logoImageUrl: "/icons/logo.svg",
          },

          variables: {
            colorText: "#fff",
            colorPrimary: "#4379EE",
            colorBackground: "#273142",
            colorInputBackground: "#53698c",
            colorInputText: "#fff",
          },
        }}
      >
        <body className={`${nunitoSans.className} bg-dark-2`}>{children}</body>
      </ClerkProvider>
    </html>
  );
}
